### ISSUE TITLE
[Documentation] Documentation is absent from gh-pages branch

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#492]
The online documentation at http://nasa.github.io/openmctweb/ seems to have gone missing, and gives a 404 now. 

Looking in the gh-pages branch I can see that only the API docs are there. Recent changes to the build process may have resulted in the documentation not being .

**Comment by akhenry** [comment]
Looking at the circle-ci build I see an error in the documentation generation (below). Appears to be a missing dependency (canvas).

Should we add `npm install canvas` to circle.yml?

```
> node docs/gendocs.js --in docs/src --out target/docs --suppress-toc 'docs/src/index.md|docs/src/process/index.md'


module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/ubuntu/openmctweb/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/openmctweb/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "run" "otherdoc"
npm ERR! node v0.10.33
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
npm ERR! open-mct-web@0.7.2 otherdoc: `node docs/gendocs.js --in docs/src --out target/docs --suppress-toc 'docs/src/index.md|docs/src/process/index.md'`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the open-mct-web@0.7.2 otherdoc script 'node docs/gendocs.js --in docs/src --out target/docs --suppress-toc 'docs/src/index.md|docs/src/process/index.md''.
npm ERR! This is most likely a problem with the open-mct-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node docs/gendocs.js --in docs/src --out target/docs --suppress-toc 'docs/src/index.md|docs/src/process/index.md'
npm ERR! You can get their info via:
npm ERR!     npm owner ls open-mct-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/openmctweb/npm-debug.log

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "run" "docs"
npm ERR! node v0.10.33
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
npm ERR! open-mct-web@0.7.2 docs: `npm run jsdoc ; npm run otherdoc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-mct-web@0.7.2 docs script 'npm run jsdoc ; npm run otherdoc'.
npm ERR! This is most likely a problem with the open-mct-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run jsdoc ; npm run otherdoc
npm ERR! You can get their info via:
npm ERR!     npm owner ls open-mct-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/openmctweb/npm-debug.log
```

**Comment by VWoeltjen** [comment]
> Should we add `npm install canvas` to circle.yml?

I believe that would fix it. (Maybe `npm install canvas nomnoml`) Want to avoid sinking much effort into this, since we'll want to discard much of this custom config at time of #225

**Comment by akhenry** [comment]
ok, I'm on it!
